### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by netugi** [DagothBob/TheGovernator#2]
Unhandled Exception:

Java.Lang.OutOfMemoryError: Failed to allocate a 
158204172 byte allocation with 16777120 free bytes and 22MB until OOM

Recreation:
play audio file, rotate screen
portrait -> landscape: screen goes black
landscape -> portrait: landscape image but at top of screen
(not sure of exact conditions, works sometimes, may have to do with memory?)

**Comment by Freia-Jensen** [comment]
Threading makes this less likely. Fixing it is too hard
